#+TITLE:       Install and Configure sqlplus on macOS
#+AUTHOR:      Jinha Kim
#+EMAIL:       jinha.kim@oracle.com
#+DATE:        2016-11-07 Mon
#+URI:         /blog/%y/%m/%d/install-and-configure-sqlplus-on-os-x
#+KEYWORDS:
#+TAGS:        osx, sqlplus
#+LANGUAGE:    en
#+PROPERTY: header-args :cache yes
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION:

* Why

In macOS, there is no trivial way to install =sqlplus=, which means there's no Homebrew package for it. You including me have to do it manually :$

* Walkthrough

  1. Download =oracle instance client for macOS= to =${tmp_dir}= from http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html. =Instant Client Package - Basic Lite=, =Instant Client Package - SQL*Plus= would suffice to run =sqlplus=.
  2. Unzip the =.zip= files. All files are inflated into =${tmp_dir}/instantclient_12_1=.
     #+BEGIN_SRC sh :var tmp_dir=(concat (getenv "HOME") "/tmp/sqlplus") :session install :results silent
       echo ${tmp_dir}
       cd ${tmp_dir}
       unzip instantclient-sqlplus-macos.x64-12.1.0.2.0.zip
       unzip instantclient-basic-macos.x64-12.1.0.2.0.zip
       cd instantclient_12_1
     #+END_SRC

  3. Link all dylibs that end with =.12.1= to those without =.12.1=
     #+BEGIN_SRC sh :session install :results silent
       for f in `ls *.12.1`
       do
           ln -sf $f `basename $f .12.1`
       done
     #+END_SRC

  4. Test to connect to a database instance.
     #+BEGIN_SRC sh :results silent
     ./sqlplus ${username}/${password}@${hostname}:${port}/${sid}
     #+END_SRC
     #+BEGIN_EXAMPLE
       SQL*Plus: Release 12.1.0.2.0 Production on Mon Nov 7 23:41:40 2016

       Copyright (c) 1982, 2016, Oracle.  All rights reserved.

       ERROR:
       ORA-21561: OID generation failed

     #+END_EXAMPLE
  5. If you try a remote connection, you might get an =ORA-21561= error. The reason is the hostname is not mapped to =127.0.0.1= [fn:1]. Edit =/private/etc/hosts= via =sudo=. To check if the change is applied, you should use =dscacheutil= command, not =host= [fn:2].
     - =/private/etc/hosts=
     #+BEGIN_EXAMPLE
       ## /private/etc/hosts
       ...
       127.0.0.1  <hostname>
       ...
     #+END_EXAMPLE
     - with =host= command
     #+BEGIN_SRC sh :session install :var hostname="joseph" :exports both :results value org replace
       host ${hostname}
     #+END_SRC

       #+RESULTS:
       #+BEGIN_SRC org

       Host joseph not found: 3(NXDOMAIN)
       #+END_SRC
     - with =dscacheutil= command
     #+BEGIN_SRC sh :session install :results value org replace :exports both
       dscacheutil -q host -a name ${hostname}
     #+END_SRC

       #+RESULTS:
       #+BEGIN_SRC org
       name: joseph
       ip_address: 127.0.0.1
       #+END_SRC

  6. Test again
     #+BEGIN_SRC sh :session install :var username="scott" :var password="tiger" :var hostname="localhost" :var port="1521" :var sid="orcl.ib.bunch" :results value org replace :exports both
     ./sqlplus ${username}/${password}@${hostname}:${port}/${sid}
     -- in sqlplus
     exit
     #+END_SRC

     #+RESULTS:
     #+BEGIN_SRC org

     sh-3.2$ sh-3.2$ sh-3.2$ sh-3.2$
     SQL*Plus: Release 12.1.0.2.0 Production on Tue Nov 8 00:01:33 2016

     Copyright (c) 1982, 2016, Oracle.  All rights reserved.

     Last Successful login time: Tue Nov 08 2016 00:01:02 -08:00

     Connected to:
     Oracle Database 12c Enterprise Edition Release 12.1.0.1.0 - 64bit Production
     With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options
     SQL> Disconnected from Oracle Database 12c Enterprise Edition Release 12.1.0.1.0 - 64bit Production
     With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options
     #+END_SRC

  7. Move the =instantclient_12_1= directory to a persistent location, append that directory to =PATH= environment variable.     cd ..
     #+BEGIN_SRC sh
     cd ..

     #+END_SRC

* Footnotes

[fn:2] http://apple.stackexchange.com/questions/158117/os-x-10-10-1-etc-hosts-private-etc-hosts-file-is-being-ignored-and-not-resol

[fn:1] http://stackoverflow.com/questions/31338916/sqlplus-remote-connection-giving-ora-21561
